# fly.toml app configuration file generated for burfield-tabata on 2023-06-26T21:52:49+10:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "burfield-tabata"
primary_region = "syd"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
